### ISSUE TITLE
Bleed poison and burn in code says 5, and in PVP lasts 5 seconds. But in PVE lasts 1 second more

### ISSUE THREAD

**Issue by Alkanov** [Alkanov/LaurumPublic#55]
We check condition expiry time every second on enemies rather than every 0.1 seconds. Depending on when was the last time the code checked timers, you could end up with 1 second more buff/debuff on enemies.

See: [checkBuffTimers](https://github.com/Alkanov/LaurumPublic/blob/2d122371305cb90bfc000273b74e3209eb8c1b0a/_public_server/EnemyConditions.cs#L463)

I would leave it like that because lowering this will definitely affect server performance.

**Comment by kevhemingway88** [comment]
yeap actually its for PVE Only and i dont care about that
in pvp almost 100% the time i tried works ok, maybe there is some difference on the code between pvp and pve, but really this is not important

**Comment by Alkanov** [comment]
The difference is that on players we check it every 0.1 seconds, on enemies we check it every 1 second.

See [Player](https://github.com/Alkanov/LaurumPublic/blob/2d122371305cb90bfc000273b74e3209eb8c1b0a/_public_server/PlayerConditions.cs#L757) and [Enemy](https://github.com/Alkanov/LaurumPublic/blob/2d122371305cb90bfc000273b74e3209eb8c1b0a/_public_server/EnemyConditions.cs#L463)

**Comment by kevhemingway88** [comment]
so one possible solution is to decrease by 1 second only in PVE the duration

**Comment by Alkanov** [comment]
Is this in 1.3-beta.8? Just asking to know if we should add it to next release

**Comment by kevhemingway88** [comment]
im gona fix it
